---
abstract: 'Reusable tests for POE::Loop authors'
author:
  - 'Rocco Caputo <rcaputo@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: POE-Test-Loops
requires:
  Test::More: '1.001003'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=POE-Test-Loops
  homepage: http://search.cpan.org/dist/POE-Test-Loops/
  repository: git://github.com/rcaputo/poe-test-loops.git
version: '1.359'
