---
abstract: 'Reusable tests for POE::Loop authors'
author:
  - 'Rocco Caputo <rcaputo@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Test-Loops
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=POE-Test-Loops
  homepage: http://search.cpan.org/dist/POE-Test-Loops/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rcaputo/poe-test-loops.git
version: 1.352
